name: Bug report
description: Create a report to help us improve
labels: ["☢️ Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Kiwi-rs version
      description: "What version of our software are you running?"
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
