[package]
name = "engine"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
rocksdb.workspace = true
snafu.workspace = true
bytes.workspace = true

[dev-dependencies]
tempfile.workspace = true