[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = { version = "0.22.0", default-features = false, features = ["zstd", "zlib", "bzip2", "lz4", "multi-threaded-cf"] }
snafu = "0.8.5"
bytes = "1.5.0"

[dev-dependencies]
tempfile = "3.8"