#!/usr/bin/env bash
# Copyright (c) 2024-present, arana-db Community.  All rights reserved.
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kiwi Raft Cluster Startup Script

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info() { echo -e "${CYAN}$1${NC}"; }
success() { echo -e "${GREEN}$1${NC}"; }
warning() { echo -e "${YELLOW}$1${NC}"; }
error() { echo -e "${RED}$1${NC}"; }

# Configuration
NODE_COUNT=3
BASE_PORT=7379
BASE_RAFT_PORT=8001
BINDING="127.0.0.1"
LOG_DIR="./cluster_logs"
DATA_DIR_PREFIX="./raft_data"

# Parse arguments
CLEAN=false
BUILD=true

while [[ $# -gt 0 ]]; do
    case $1 in
        --clean)
            CLEAN=true
            shift
            ;;
        --no-build)
            BUILD=false
            shift
            ;;
        --nodes)
            NODE_COUNT=$2
            shift 2
            ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --clean      Clean data directories before starting"
            echo "  --no-build   Skip building the project"
            echo "  --nodes N    Number of nodes to start (default: 3)"
            echo "  --help       Show this help message"
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Banner
info "=== Kiwi Raft Cluster Startup ==="
echo ""

# Clean old data if requested
if [ "$CLEAN" = true ]; then
    warning "Cleaning old cluster data..."
    rm -rf ${DATA_DIR_PREFIX}_*
    rm -rf ${LOG_DIR}
    rm -f cluster_node*.conf
    success "✓ Cleaned"
    echo ""
fi

# Build the project
if [ "$BUILD" = true ]; then
    info "Building Kiwi..."
    cargo build --release
    if [ $? -ne 0 ]; then
        error "Build failed!"
        exit 1
    fi
    success "✓ Build complete"
    echo ""
fi

# Create log directory
mkdir -p ${LOG_DIR}

# Generate configuration files
info "Generating configuration files for ${NODE_COUNT} nodes..."
for i in $(seq 1 $NODE_COUNT); do
    PORT=$((BASE_PORT + i - 1))
    RAFT_PORT=$((BASE_RAFT_PORT + i - 1))
    CONFIG_FILE="cluster_node${i}.conf"
    
    cat > ${CONFIG_FILE} << EOF
# Kiwi Cluster Node ${i} Configuration
# Auto-generated by start_cluster.sh

# Basic server settings
port ${PORT}
binding ${BINDING}

# Database path (each node needs its own)
db-path ./db_node${i}

# Raft configuration
raft-node-id ${i}
raft-addr ${BINDING}:${RAFT_PORT}
raft-resp-addr ${BINDING}:${PORT}
raft-data-dir ${DATA_DIR_PREFIX}_${i}

# Storage settings
memory 1GB
rocksdb-max-background-jobs 4
rocksdb-max-write-buffer-number 2
rocksdb-write-buffer-size 67108864

# Logging
log-dir ${LOG_DIR}
EOF
    
    success "  ✓ Generated ${CONFIG_FILE}"
done
echo ""

# Start nodes
info "Starting ${NODE_COUNT} Raft nodes..."
PIDS=()

for i in $(seq 1 $NODE_COUNT); do
    PORT=$((BASE_PORT + i - 1))
    RAFT_PORT=$((BASE_RAFT_PORT + i - 1))
    CONFIG_FILE="cluster_node${i}.conf"
    LOG_FILE="${LOG_DIR}/node${i}.log"
    
    # Start node in background
    RUST_LOG=info cargo run --release --bin kiwi -- --config ${CONFIG_FILE} > ${LOG_FILE} 2>&1 &
    PID=$!
    PIDS+=($PID)
    
    success "  ✓ Node ${i} started (PID: ${PID})"
    info "    - Redis: ${BINDING}:${PORT}"
    info "    - Raft:  ${BINDING}:${RAFT_PORT}"
    info "    - Log:   ${LOG_FILE}"
    
    # Wait a bit before starting next node
    sleep 1
done

echo ""
success "=== Cluster Started Successfully ==="
echo ""
info "Cluster Information:"
info "  Nodes:     ${NODE_COUNT}"
info "  Log Dir:   ${LOG_DIR}"
info "  Data Dirs: ${DATA_DIR_PREFIX}_1 to ${DATA_DIR_PREFIX}_${NODE_COUNT}"
echo ""
info "To stop the cluster, run:"
info "  kill ${PIDS[@]}"
echo ""
info "Or use the stop script:"
info "  ./scripts/stop_cluster.sh"
echo ""

# Save PIDs to file for stop script
echo "${PIDS[@]}" > ${LOG_DIR}/cluster.pids

# Monitor logs
info "Monitoring cluster startup (Ctrl+C to stop monitoring)..."
info "Logs will continue in background"
echo ""
sleep 2

# Show recent logs from all nodes
for i in $(seq 1 $NODE_COUNT); do
    LOG_FILE="${LOG_DIR}/node${i}.log"
    if [ -f ${LOG_FILE} ]; then
        info "=== Node ${i} Recent Logs ==="
        tail -n 5 ${LOG_FILE} || true
        echo ""
    fi
done

info "Cluster is running. Check logs in ${LOG_DIR}/ for details."
info "Press Ctrl+C to exit (cluster will continue running)"

# Keep script running to show logs
trap 'echo ""; info "Monitoring stopped. Cluster is still running."; exit 0' INT

# Tail all logs
tail -f ${LOG_DIR}/node*.log
