# Copyright (c) 2024-present, Qihoo, Inc.  All rights reserved.
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

INCLUDE(ExternalProject)

SET(REDISCACHE_SOURCES_DIR ${THIRD_PARTY_PATH}/rediscache)
SET(REDISCACHE_INSTALL_DIR ${THIRD_PARTY_PATH}/install/rediscache)
SET(REDISCACHE_INCLUDE_DIR "${REDISCACHE_INSTALL_DIR}/include" CACHE PATH "rediscache include directory." FORCE)
SET(REDISCACHE_LIBRARIES "${REDISCACHE_INSTALL_DIR}/lib/librediscache.a" CACHE FILEPATH "rediscache library." FORCE)

SET(prefix_path "${THIRD_PARTY_PATH}/install/brpc|${CMAKE_CURRENT_BINARY_DIR}/_deps/gflags-build|${THIRD_PARTY_PATH}/install/protobuf|${THIRD_PARTY_PATH}/install/zlib|${THIRD_PARTY_PATH}/install/leveldb")

ExternalProject_Add(
  extern_rediscache
  ${EXTERNAL_PROJECT_LOG_ARGS}
  URL https://github.com/pikiwidb/rediscache/archive/refs/tags/v1.0.7.tar.gz
  URL_HASH MD5=02c8aadc018dd8d4d3803cc420d1d75b
  PREFIX ${REDISCACHE_SOURCES_DIR}
  UPDATE_COMMAND ""
  CMAKE_ARGS -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
  -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}
  -DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}
  -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
  -DCMAKE_C_FLAGS_DEBUG=${CMAKE_C_FLAGS_DEBUG}
  -DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
  -DCMAKE_INSTALL_PREFIX=${REDISCACHE_INSTALL_DIR}
  -DCMAKE_INSTALL_LIBDIR=${REDISCACHE_INSTALL_DIR}/lib
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  -DSNAPPY_BUILD_TESTS=OFF
  -DCMAKE_BUILD_TYPE=${THIRD_PARTY_BUILD_TYPE}
  -DCMAKE_PREFIX_PATH=${prefix_path}
  ${EXTERNAL_OPTIONAL_ARGS}
  CMAKE_CACHE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${REDISCACHE_INSTALL_DIR}
  -DCMAKE_INSTALL_LIBDIR:PATH=${REDISCACHE_INSTALL_DIR}/lib
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
  -DCMAKE_BUILD_TYPE:STRING=${THIRD_PARTY_BUILD_TYPE}
  BUILD_COMMAND 
  make -j${CPU_CORE}
  INSTALL_COMMAND mkdir -p ${REDISCACHE_INSTALL_DIR}/lib/ COMMAND cp ${REDISCACHE_SOURCES_DIR}/src/extern_rediscache-build/librediscache.a ${REDISCACHE_LIBRARIES} COMMAND mkdir -p ${REDISCACHE_INCLUDE_DIR} COMMAND cp -rf ${REDISCACHE_SOURCES_DIR}/src/extern_rediscache ${REDISCACHE_INCLUDE_DIR}/rediscache/ 
)

ADD_LIBRARY(rediscache STATIC IMPORTED GLOBAL)
SET_PROPERTY(TARGET rediscache PROPERTY IMPORTED_LOCATION ${REDISCACHE_LIBRARIES})
ADD_DEPENDENCIES(rediscache extern_rediscache)