[package]
name = "net"
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
log.workspace = true
tokio.workspace = true
storage.workspace = true
async-trait = "0.1"
snafu = "0.8"
bitflags = "2.9.1"
